version: '3.8'
services:
  app:
    container_name: myfirst_dockerized_rest_server
    build:
      dockerfile: rest_api/Dockerfile
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    container_name: myfirst_dockerized_database_server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "world"
      MYSQL_USER: "newuser"          
      MYSQL_PASSWORD: "newpassword"
    volumes:
      - ./db_dumps/world.sql:/docker-entrypoint-initdb.d/world.sql
